# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3bca8261d96707e04000c5e1871e55a6fca7799d8bb6facd3a3ba962f0c3fa4f34e987670952cd450d43e7c1738cf2871efcf4c6fe5ccece4539b9b5f4d5e002

test:
  secret_key_base: 340577bf9190bd1b2653b4aefc392fe087c03a16717906aaf1b6aae97c48a559b44d681659d2d3876e0b8d0a81c6ee900e3b69ee03e88230c198f53dadf0b59d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
